### ISSUE TITLE
Allow nested locale config files

### ISSUE THREAD

**Issue by jeznag** [shaiguitar/haml-i18n-extractor#24]
When working with very large websites, having all the i18n config in one file is overwhelming. From a translation perspective, it's easier to work with individual files for each view.

I've added a feature to support this:
https://github.com/shaiguitar/haml-i18n-extractor/pull/23

**Comment by shaiguitar** [comment]
Hey @jeznag - thanks! I haven't used this gem in a while so you probably have the better perspective on usability than me at this point.
